name: GitHub-Profile-Trophy

on:
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: get-trophy

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python get-trophy.py
      - run: |   
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generate profile trophy"
          git push